// Code generated by "dataclass -type Event -field Level Level,Format string,Args []any -output event_generated.go"; DO NOT EDIT.

package logger

type Event interface {
	Level() Level
	Format() string
	Args() []any
}
type event struct {
	level  Level
	format string
	args   []any
}

func (s *event) Level() Level   { return s.level }
func (s *event) Format() string { return s.format }
func (s *event) Args() []any    { return s.args }
func NewEvent(
	level Level,
	format string,
	args []any,
) Event {
	return &event{
		level:  level,
		format: format,
		args:   args,
	}
}
